# Generated by Django 3.1 on 2020-08-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'hosts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=128, verbose_name='Serial Number')),
                ('size_gb', models.IntegerField(verbose_name='Size (GB)')),
                ('interface', models.CharField(blank=True, choices=[('IDE', 'IDE'), ('eSATA', 'eSATA'), ('PCIe', 'PCIe'), ('SATA', 'SATA'), ('SAS', 'SAS'), ('USB', 'USB')], max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='host_disks', to='diskapp.host')),
            ],
            options={
                'verbose_name_plural': 'Disks',
                'db_table': 'disks',
                'ordering': ['size_gb', 'serial_no'],
            },
        ),
    ]
